source "http://rubygems.org"

gem 'capybara', '~> 3.3'
gem 'cucumber', '~> 3.2'
gem 'faker'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'pry'
gem 'report_builder'
gem 'json'
gem 'capybara-screenshot'
gem 'yaml'
gem 'report_builder'
gem 'ffi'
gem 'json'
gem 'rake'
gem 'tiny_tds'
gem 'fileutils'
gem 'br_documents'
gem 'ffaker'
gem 'brazilian_documents', '~> 0.1.4'
gem 'cpf_cnpj', '~> 0.2.1'